INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (1, '2024-01-01', 100);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (2, '2024-01-02', 200);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (3, '2024-02-03', 50);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (4, '2024-01-04', 75);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (5, '2024-04-05', 125);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (6, '2024-03-06', 150);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (7, '2024-01-07', 100);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (8, '2024-05-08', 200);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (9, '2024-05-09', 50);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (10, '2024-02-10', 75);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (1, '2024-01-11', 125);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (2, '2024-01-12', 150);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (3, '2024-01-13', 100);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (4, '2024-01-14', 200);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (5, '2024-01-15', 50);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (6, '2024-07-16', 75);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (7, '2024-07-17', 125);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (8, '2024-01-18', 150);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (9, '2024-02-19', 100);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (10, '2024-01-20', 200);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (1, '2024-05-21', 50);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (2, '2024-01-22', 75);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (3, '2024-04-23', 125);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (4, '2024-04-24', 150);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (5, '2024-01-25', 100);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (6, '2024-03-26', 200);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (7, '2024-03-27', 50);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (8, '2024-06-28', 75);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (9, '2024-07-29', 125);
INSERT INTO Orders (CustomerID, OrderDate, Total) VALUES (10, '2024-07-30', 3000);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (1, 1, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (1, 2, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (2, 3, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (2, 4, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (3, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (3, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (4, 7, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (4, 8, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (5, 9, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (5, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 20, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (6, 1, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (6, 3, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (7, 4, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (7, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 18, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (8, 2, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (8, 6, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (9, 7, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (9, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (10, 9, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (10, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (11, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (11, 3, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (12, 4, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (12, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 20, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 9, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 3, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 4, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 19, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (24, 14, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (24, 16, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (25, 17, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (25, 18, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (26, 19, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (26, 20, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (27, 1, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (27, 3, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (28, 4, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (28, 5, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 20, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 9, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 3, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 4, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (17, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (17, 7, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (18, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (18, 9, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (19, 10, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (19, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (20, 2, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (20, 3, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (21, 4, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (21, 5, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (22, 6, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (22, 7, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (23, 8, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (23, 9, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (24, 10, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (24, 1, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (25, 2, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (25, 3, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (26, 4, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (26, 5, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (27, 6, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (27, 7, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (28, 8, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (28, 9, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (29, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (29, 1, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 2, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (30, 3, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (1, 4, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (1, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (2, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (2, 7, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (2, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (3, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (3, 9, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (4, 10, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (4, 1, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (5, 2, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (5, 3, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (6, 4, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (6, 5, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (7, 6, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (7, 7, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (8, 8, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (8, 9, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (9, 10, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (9, 1, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (10, 2, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (10, 3, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (11, 4, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (11, 5, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (12, 6, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (12, 7, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 8, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (13, 9, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 10, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (14, 1, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 2, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (15, 3, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 4, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (16, 5, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (17, 6, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (17, 7, 3);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (18, 8, 1);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (18, 9, 2);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (19, 10, 3);

--update para el unitPrice de orderDetails
UPDATE OrderDetails
SET UnitPrice = P.Price
FROM OrderDetails OD
INNER JOIN Products P ON OD.ProductID = P.ProductID;


INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (1, 'Tarjeta', '2024-01-01');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (1, 'Efectivo', '2024-01-02');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (2, 'Transferencia', '2024-01-03');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (3, 'Tarjeta', '2024-01-04');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (3, 'Efectivo', '2024-01-05');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (4, 'Transferencia', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (5, 'Tarjeta', '2024-01-07');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (5, 'Efectivo', '2024-01-08');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (5, 'Transferencia', '2024-01-09');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (6, 'Tarjeta', '2024-01-10');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (30, 'Transferencia', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (7, 'Tarjeta', '2024-01-12');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (8, 'Efectivo', '2024-01-13');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (9, 'Transferencia', '2024-01-14');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (10, 'Tarjeta', '2024-01-15');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (11, 'Efectivo', '2024-01-16');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (12, 'Transferencia', '2024-01-17');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (13, 'Tarjeta', '2024-01-18');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (14, 'Efectivo', '2024-01-19');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (15, 'Transferencia', '2024-01-20');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (30, 'Transferencia', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (16, 'Tarjeta', '2024-01-22');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (17, 'Efectivo', '2024-01-23');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (18, 'Transferencia', '2024-01-24');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (19, 'Tarjeta', '2024-01-25');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (20, 'Efectivo', '2024-01-26');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (21, 'Transferencia', '2024-01-27');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (22, 'Tarjeta', '2024-01-28');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (23, 'Efectivo', '2024-01-29');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (24, 'Transferencia', '2024-01-29');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (30, 'Transferencia', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (25, 'Tarjeta', '2024-01-02');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (26, 'Efectivo', '2024-01-03');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (27, 'Transferencia', '2024-01-04');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (28, 'Tarjeta', '2024-01-05');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (29, 'Efectivo', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (30, 'Transferencia', '2024-01-07');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (1, 'Tarjeta', '2024-01-08');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (2, 'Efectivo', '2024-01-09');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (3, 'Transferencia', '2024-01-04');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (4, 'Tarjeta', '2024-01-01');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (5, 'Efectivo', '2024-01-02');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (6, 'Transferencia', '2024-01-03');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (7, 'Tarjeta', '2024-01-04');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (8, 'Efectivo', '2024-01-05');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (9, 'Transferencia', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (10, 'Tarjeta', '2024-01-07');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (11, 'Efectivo', '2024-01-08');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (12, 'Transferencia', '2024-01-09');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (13, 'Tarjeta', '2024-01-10');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (14, 'Efectivo', '2024-01-01');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (15, 'Transferencia', '2024-01-02');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (16, 'Tarjeta', '2024-01-03');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (17, 'Efectivo', '2024-01-04');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (18, 'Transferencia', '2024-01-05');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (19, 'Tarjeta', '2024-01-06');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (20, 'Efectivo', '2024-01-07');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (21, 'Transferencia', '2024-01-08');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (22, 'Tarjeta', '2024-01-09');
INSERT INTO Payments (OrderID, PaymentMethod, PaymentDate) VALUES (23, 'Efectivo', '2024-01-06');

--crear inserts para Amount de Payments

INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (1, 'En proceso', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (1, 'Enviado', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (2, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (2, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (3, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (3, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (4, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (4, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (5, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (5, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Entregado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (6, 'En proceso', '2024-01-12');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (6, 'Enviado', '2024-01-14');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (7, 'En proceso', '2024-01-13');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (7, 'Enviado', '2024-01-15');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (8, 'En proceso', '2024-01-14');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (8, 'Enviado', '2024-01-16');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (9, 'En proceso', '2024-01-15');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (9, 'Enviado', '2024-01-17');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (10, 'En proceso', '2024-01-16');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Entregado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (11, 'En proceso', '2024-01-22');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (11, 'Enviado', '2024-01-24');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (12, 'En proceso', '2024-01-23');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (12, 'Enviado', '2024-01-25');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (13, 'En proceso', '2024-01-24');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (13, 'Enviado', '2024-01-26');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (14, 'En proceso', '2024-01-25');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (14, 'Enviado', '2024-01-27');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (15, 'En proceso', '2024-01-26');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Entregado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (16, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (16, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (17, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (17, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (18, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (18, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (19, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (19, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (20, 'En proceso', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Entregado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (21, 'En proceso', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (21, 'Enviado', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (22, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (22, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (23, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (23, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (24, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (24, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (25, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (25, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Entregado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (21, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (21, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (22, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (22, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (23, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (23, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (24, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (24, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (25, 'En proceso', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (25, 'Enviado', '2024-01-08');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (26, 'En proceso', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (26, 'Enviado', '2024-01-09');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (27, 'En proceso', '2024-01-08');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (27, 'Enviado', '2024-01-10');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (28, 'En proceso', '2024-01-09');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (28, 'Enviado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (29, 'En proceso', '2024-01-10');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (29, 'Enviado', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'En proceso', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (30, 'Enviado', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (1, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (1, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (2, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (2, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (3, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (3, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (4, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (4, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (5, 'En proceso', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (5, 'Enviado', '2024-01-08');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (6, 'En proceso', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (6, 'Enviado', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (7, 'En proceso', '2024-01-03');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (7, 'Enviado', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (8, 'En proceso', '2024-01-04');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (8, 'Enviado', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (9, 'En proceso', '2024-01-05');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (9, 'Enviado', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (10, 'En proceso', '2024-01-06');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (10, 'Enviado', '2024-01-08');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (11, 'En proceso', '2024-01-07');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (11, 'Enviado', '2024-01-09');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (12, 'En proceso', '2024-01-08');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (12, 'Enviado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (13, 'En proceso', '2024-01-09');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (13, 'Enviado', '2024-01-01');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (14, 'En proceso', '2024-01-00');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (14, 'Enviado', '2024-01-02');
INSERT INTO OrderStatus (OrderID, Status, Date) VALUES (15, 'Entregado', '2024-01-07');


INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (1, '2024-01-05', 'DHL', '1234567890');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (3, '2024-02-07', 'UPS', '9876543210');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (5, '2024-02-09', 'FedEx', '1111111111');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (7, '2024-03-11', 'DHL', '2222222222');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (9, '2024-01-13', 'UPS', '3333333333');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (11, '2024-05-15', 'FedEx', '4444444444');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (13, '2024-04-17', 'DHL', '5555555555');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (15, '2024-07-19', 'UPS', '6666666666');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (17, '2024-03-21', 'FedEx', '7777777777');
INSERT INTO Shipping (OrderID, Date, Carrier, TrackingNumber) VALUES (19, '2024-05-23', 'DHL', '8888888888');


INSERT INTO Returns (OrderID, Date, Reason) VALUES (5, '2024-05-12', 'Defectuoso');
INSERT INTO Returns (OrderID, Date, Reason) VALUES (11, '2024-02-18', 'No corresponde a la descripción');
INSERT INTO Returns (OrderID, Date, Reason) VALUES (19, '2024-03-25', 'Cambió de opinión');


INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 1, 5, 'Excelente producto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (4, 4, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 5, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (6, 6, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (7, 7, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (8, 8, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (9, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (10, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (11, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (12, 4, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (13, 5, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 6, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 7, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 8, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 9, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (4, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (6, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (7, 4, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (8, 5, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (9, 6, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (14, 8, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (15, 9, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (16, 10, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 1, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (6, 2, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (7, 3, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 5, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 6, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 7, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (10, 2, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (11, 3, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (12, 4, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 9, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (19, 10, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (15, 8, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (16, 2, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (17, 3, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 4, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (10, 6, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (11, 7, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (12, 8, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (19, 1, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 2, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 3, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (15, 10, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 4, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 5, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (4, 6, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (12, 1, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (13, 2, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (14, 3, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (19, 8, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 9, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 10, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 7, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (6, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (7, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (15, 6, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (16, 7, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (17, 8, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 4, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 5, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 6, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 9, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 7, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (4, 8, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 9, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (14, 2, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (15, 3, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (16, 4, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 10, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (17, 9, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 10, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (19, 1, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 5, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 6, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 7, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 8, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (18, 3, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (19, 4, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (20, 5, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (1, 9, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (2, 10, 4, 'Muy satisfactorio');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (3, 1, 5, 'Excelente');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (4, 2, 4, 'Muy bueno');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (5, 3, 5, 'Perfecto');
INSERT INTO ProductReviews (ProductID, CustomerID, Rating, Review) VALUES (6, 4, 4, 'Muy satisfactorio');